'use client'

import { useState } from 'react'
import { ArrowUpRight, Check } from 'lucide-react'
import { Button, Footer, PageShell } from './site-shell'
import { Hero, SignatureBreak } from './content-sections'

export function ContactForm() { const [sent, setSent] = useState(false); if (sent) return <div className="success-state"><div><Check size={28} /></div><h2>We&apos;ll be in touch.</h2><p>Thank you for reaching out. Your message has found its way to us.</p><button onClick={() => setSent(false)}>Send another message</button></div>; return <form className="contact-form" onSubmit={(event) => { event.preventDefault(); setSent(true) }}><label>Name<input required name="name" placeholder="Your name" /></label><label>Email<input required type="email" name="email" placeholder="you@example.com" /></label><label>Message<textarea required name="message" placeholder="Tell us a little more" rows={4} /></label><button className="editorial-button" type="submit">Send message <ArrowUpRight size={15} /></button></form> }

export function AboutPage() { return <PageShell><main><Hero eyebrow="THE HOUSE / EST. 2024" title={<>CLOTHES WITH<br /><i>A POINT OF VIEW.</i></>} description="An independent fashion label for those who stand out." image="https://images.unsplash.com/photo-1496217590455-aa63a8350eea?auto=format&fit=crop&w=2200&q=85" cta="Read our story" href="#about-story" /><section className="about-story section-pad" id="about-story"><p className="eyebrow">01 / OUR PHILOSOPHY</p><h2>FASHION ISN&apos;T<br />JUST WHAT YOU WEAR.<br /><i>IT&apos;S HOW YOU MOVE</i><br />THROUGH THE WORLD.</h2><div className="about-grid"><img src="https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&w=1200&q=85" alt="Jeilees studio portrait" /><p className="large-copy">We believe in clothes that tell your story. In a world of more, we choose bold: striking prints, honest materials, and a creative kind of ambition.<br /><br /><span className="body-copy">Our collections are designed with passion and made with a small, trusted network of makers. We are interested in the intersection of fandom and fashion — the things you love, made wearable.</span></p></div></section><SignatureBreak /><Footer /></main></PageShell> }

export function ContactPage() { return <PageShell dark><main><section className="contact-hero"><p className="eyebrow">GET IN TOUCH</p><h1>LET&apos;S<br /><i>TALK.</i></h1><p>For press, partnerships, stockists, or simply to say hello.</p></section><section className="contact-body section-pad"><div><p className="eyebrow">02 / START A CONVERSATION</p><h2>Tell us<br /><i>everything.</i></h2><p className="body-copy">We read every message. Share a thought, a project, or a question and we&apos;ll get back to you soon.</p></div><ContactForm /></section><Footer /></main></PageShell> }
