'use client'

import { useState } from 'react'
import { ArrowUpRight, Check } from 'lucide-react'
import { collections, products, type CollectionKey } from '@/lib/fashion-data'
import { Button, Footer, PageShell } from './site-shell'
import { Hero, SignatureBreak, ShopShowcase } from './content-sections'
import { ProductImage } from './product-image'

export function ContactForm() { const [sent, setSent] = useState(false); if (sent) return <div className="success-state"><div><Check size={28} /></div><h2>We&apos;ll be in touch.</h2><p>Thank you for reaching out. Your message has found its way to us.</p><button onClick={() => setSent(false)}>Send another message</button></div>; return <form className="contact-form" onSubmit={(event) => { event.preventDefault(); setSent(true) }}><label>Name<input required name="name" placeholder="Your name" /></label><label>Email<input required type="email" name="email" placeholder="you@example.com" /></label><label>Message<textarea required name="message" placeholder="Tell us a little more" rows={4} /></label><button className="editorial-button" type="submit">Send message <ArrowUpRight size={15} /></button></form> }

export function CollectionPage({ kind }: { kind: CollectionKey }) { const collectionData = collections[kind]; const collectionProducts = products.filter((product) => product.collection === kind); return <PageShell><main><Hero eyebrow={collectionData.label} title={kind === 'men' ? <>THE<br /><i>MODERN MAN.</i></> : kind === 'women' ? <>DEFINE<br /><i>YOUR STYLE.</i></> : <>SMALL STYLE.<br /><i>BIG ENERGY.</i></>} description={collectionData.description} image={collectionData.image} cta={`Explore ${kind}`} href="#pieces" /><section className={`collection-intro collection-intro-${kind} section-pad`} id="pieces"><p className="eyebrow">THE {kind.toUpperCase()} EDIT / 2025</p><h2>{collectionData.title}</h2><p>{collectionData.description} This season, we are looking at the space between structure and ease — pieces that become part of your own signature.</p></section><div className="collection-products">{collectionProducts.map((product, index) => <article key={product.name} className="collection-piece"><ProductImage src={product.image} fallback={product.fallbackImage} alt={product.imageAlt} priority={index === 0} /><div><p className="eyebrow">0{index + 1} / {product.category}</p><h3>{product.name}</h3><Button href="/contact">Enquire</Button></div></article>)}</div><ShopShowcase collection={kind} /><SignatureBreak /><Footer /></main></PageShell> }

export function AboutPage() { return <PageShell><main><Hero eyebrow="THE HOUSE / EST. 2018" title={<>CLOTHES WITH<br /><i>A POINT OF VIEW.</i></>} description="An independent fashion house for considered lives." image="https://images.unsplash.com/photo-1496217590455-aa63a8350eea?auto=format&fit=crop&w=2200&q=85" cta="Read our story" href="#about-story" /><section className="about-story section-pad" id="about-story"><p className="eyebrow">01 / OUR PHILOSOPHY</p><h2>FASHION ISN&apos;T<br />JUST WHAT YOU WEAR.<br /><i>IT&apos;S HOW YOU MOVE</i><br />THROUGH THE WORLD.</h2><div className="about-grid"><img src="https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&w=1200&q=85" alt="VERRA studio portrait" /><p className="large-copy">We believe in clothes that stay with you. In a world of more, we choose better: precise cuts, honest materials, and a slower kind of ambition.<br /><br /><span className="body-copy">Our collections are designed in London and made with a small, trusted network of makers. We are interested in the tension between utility and beauty — the things you need, made extraordinary.</span></p></div></section><SignatureBreak /><Footer /></main></PageShell> }

export function ContactPage() { return <PageShell dark><main><section className="contact-hero"><p className="eyebrow">GET IN TOUCH</p><h1>LET&apos;S<br /><i>TALK.</i></h1><p>For press, partnerships, stockists, or simply to say hello.</p></section><section className="contact-body section-pad"><div><p className="eyebrow">02 / START A CONVERSATION</p><h2>Tell us<br /><i>everything.</i></h2><p className="body-copy">We read every message. Share a thought, a project, or a question and we&apos;ll get back to you soon.</p></div><ContactForm /></section><Footer /></main></PageShell> }
